/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package themaze;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractAction;
import javax.swing.Timer;

/**
 *
 * @author 073787251
 */
public class GameBoard extends javax.swing.JPanel {
    int px = 0, py = 0; //Player x and y positions
    /**
     * Creates new form GameBoard
     */
    public GameBoard() {
        initComponents();
    }

    public void anim() {
        Timer t1 = new Timer(17, new TimerListener());
        t1.start();
    }

    public void drawBoard(Graphics g) {
        for (Square s : MainFrame.board) {
            s.display(g);
        }
        for (int i = 0; i < 750; i += 50) {
            g.setColor(Color.BLACK);
            g.drawLine(i, 0, i, 750);
        }
        for (int i = 0; i < 750; i += 50) {
            g.setColor(Color.BLACK);
            g.drawLine(0, i, 750, i);
        }
        g.setColor(Color.RED);
        g.fillOval(px, py, 50, 50);
        if (MainFrame.gameMode == 0) {
            g.drawRect(Square.hovX,Square.hovY,50,50);
        }
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        drawBoard(g);

    }

    @Override
    public void paint(Graphics g) {
        paintComponent(g);
        drawBoard(g);
    }

    private class TimerListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            repaint();
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(750, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
